package managePackage;

import StudentPackage.MyFunction;
import StudentPackage.MainForm;
import StudentPackage.course;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ManageCrsForm extends javax.swing.JFrame {

    course cr = new course();
    DefaultTableModel model;
        
    public ManageCrsForm() {    
        initComponents();
        
        cr.fillCourseJtable(jTableCourse, "");
        
        model = (DefaultTableModel)jTableCourse.getModel();
      
        jTableCourse.setRowHeight(30);
        jTableCourse.setShowGrid(true);
        jTableCourse.setGridColor(Color.getHSBColor(199, 238, 144));
        jTableCourse.setSelectionBackground(Color.getHSBColor(152, 251, 152));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerHours = new javax.swing.JSpinner();
        jTextField1_Id = new javax.swing.JTextField();
        jButtonAddCourse = new javax.swing.JButton();
        jButtonCancel1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCourse = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValueToSearch = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jTextField1_label = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Manage");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Id:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Hours:");

        jSpinnerHours.setModel(new javax.swing.SpinnerNumberModel(5, 4, 300, 1));

        jTextField1_Id.setForeground(new java.awt.Color(0, 51, 51));
        jTextField1_Id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_IdActionPerformed(evt);
            }
        });

        jButtonAddCourse.setBackground(new java.awt.Color(153, 153, 255));
        jButtonAddCourse.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jButtonAddCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        jButtonAddCourse.setText("Add");
        jButtonAddCourse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCourseActionPerformed(evt);
            }
        });

        jButtonCancel1.setBackground(new java.awt.Color(255, 153, 153));
        jButtonCancel1.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jButtonCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minus.png"))); // NOI18N
        jButtonCancel1.setText("Delete");
        jButtonCancel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel1ActionPerformed(evt);
            }
        });

        jTableCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Label", "Hours"
            }
        ));
        jTableCourse.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCourseMouseClicked(evt);
            }
        });
        jTableCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableCourseKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCourse);
        if (jTableCourse.getColumnModel().getColumnCount() > 0) {
            jTableCourse.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("Value to Search: ");

        jTextFieldValueToSearch.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 51));
        jButtonUpdate.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jTextField1_label.setForeground(new java.awt.Color(0, 51, 51));
        jTextField1_label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_labelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Course:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField1_Id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                        .addComponent(jTextField1_label))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValueToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAddCourse, jButtonCancel1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldValueToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_Id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerHours, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_IdActionPerformed

    
    public boolean verifyText(){
       if (jTextField1_Id.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Please Enter a valid Value");
           return false;
       }
       else {
           return true;
       }
    }
    
    private void jButtonAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCourseActionPerformed
        // if not equal to nothing
        if (!jTextField1_label.getText().equals("")){
            // If course doesn't exist then insert
            if (!cr.isCourseExist(jTextField1_label.getText())){
                // get input from course TextField
                String label = jTextField1_label.getText();
                int hours = Integer.valueOf(jSpinnerHours.getValue().toString());

                cr.insertUpdateDeleteCourse('i', null, label, hours);
                
                // update table after modified its
                ManageCrsForm.jTableCourse.setModel(new DefaultTableModel(null, new Object[] {"id","label","hours"}));
                cr.fillCourseJtable(ManageCrsForm.jTableCourse, "");
                MainForm.jLabel2_crsCount.setText(" Course Count : " + Integer.toString(MyFunction.countData("course")));

            }

            // duplicate label
            else{
                JOptionPane.showMessageDialog(null, "Course Already Exist");
            } 
        }
        
        // null input
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Something Darling");
        }

    }//GEN-LAST:event_jButtonAddCourseActionPerformed

    private void jButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel1ActionPerformed
        if (jTextField1_Id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No Course Selected");
        }
        else {
            // xóa dựa theo Id
            int id = Integer.valueOf(jTextField1_Id.getText());

            cr.insertUpdateDeleteCourse('d', id, null, null);
            // re-count student from table

            ManageCrsForm.jTableCourse.setModel(new DefaultTableModel(null, new Object[] {"id","label","hours"}));
            cr.fillCourseJtable(ManageCrsForm.jTableCourse, "");
            MainForm.jLabel2_crsCount.setText("Course Count: " + Integer.toString(MyFunction.countData("course")));

            // Set all input row to be Empty again
            jTextField1_label.setText("");
            jSpinnerHours.setValue(5);
            jTextField1_Id.setText("");
        }
    }//GEN-LAST:event_jButtonCancel1ActionPerformed
    
   
    
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        
        if (verifyText()){
            // get input from course TextField  
            int id = Integer.valueOf(jTextField1_Id.getText());
            String label = jTextField1_label.getText();
            int hours = Integer.valueOf(jSpinnerHours.getValue().toString());


            cr.insertUpdateDeleteCourse('u', id, label, hours);
            // update table after modified its
            ManageCrsForm.jTableCourse.setModel(new DefaultTableModel(null, new Object[] {"id","label","hours"}));
            cr.fillCourseJtable(ManageCrsForm.jTableCourse, "");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTableCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCourseMouseClicked
        // get data from selected row
        int index = jTableCourse.getSelectedRow();
        // get value from row at index ? and row ? to refer TextField
        // toString() because TextField is String type
        jTextField1_Id.setText(jTableCourse.getValueAt(index, 0).toString());
        jTextField1_label. setText(jTableCourse.getValueAt(index, 1).toString());
        jSpinnerHours.setValue(Integer.valueOf(jTableCourse.getValueAt(index, 2).toString() ));
    }//GEN-LAST:event_jTableCourseMouseClicked

    private void jTextField1_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_labelActionPerformed

    private void jTableCourseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCourseKeyReleased
        // Set new Table with new Input each Update
        // While Arrow Key moving Up or Down info Appear at Input
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){

            int rowIndex = jTableCourse.getSelectedRow();
            jTextField1_Id.setText(jTableCourse.getValueAt(rowIndex, 0).toString());
            jTextField1_label. setText(jTableCourse.getValueAt(rowIndex, 1).toString());
            jSpinnerHours.setValue(Integer.valueOf(jTableCourse.getValueAt(rowIndex, 2).toString() ));
            
        }        
    }//GEN-LAST:event_jTableCourseKeyReleased


    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCrsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCourse;
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerHours;
    public static javax.swing.JTable jTableCourse;
    private javax.swing.JTextField jTextField1_Id;
    private javax.swing.JTextField jTextField1_label;
    private javax.swing.JTextField jTextFieldValueToSearch;
    // End of variables declaration//GEN-END:variables
}
