package managePackage;

import StudentPackage.MyFunction;
import StudentPackage.MainForm;
import StudentPackage.student;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ManageStdForm2 extends javax.swing.JFrame {

    student std = new student();
    DefaultTableModel model;
    
    public ManageStdForm2() {
        
        initComponents();
        
        
        std.fillStudentJtable(jTableStd, "");
        
        // gender btn. Set Default to Male
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMale);
        bg.add(jRadioButtonFemale);
        jRadioButtonMale.setSelected(true);
        
        // Beautify Table UI
        model = (DefaultTableModel)jTableStd.getModel();
        jTableStd.setRowHeight(27);
        jTableStd.setShowGrid(true);
        jTableStd.setGridColor(Color.getHSBColor(199, 238, 144));
        jTableStd.setSelectionBackground(Color.getHSBColor(152, 251, 152));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_LastName = new javax.swing.JTextField();
        jTextField1_Val_FindKey = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jDateChooserBirthDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jButtonAddStudent = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStd = new javax.swing.JTable();
        jTextField1_FirstName = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1_stdID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(108, 116, 112));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 249, 88));
        jLabel1.setText("New Student");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 338, 90));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 249, 88));
        jLabel2.setText("First Name: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 249, 88));
        jLabel3.setText("Last Name: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 249, 88));
        jLabel4.setText("Sex: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 249, 88));
        jLabel5.setText("BirthDate: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(77, 249, 88));
        jLabel6.setText("Phone: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(77, 249, 88));
        jLabel7.setText("Address: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jTextField1_LastName.setBackground(new java.awt.Color(192, 246, 219));
        jTextField1_LastName.setForeground(new java.awt.Color(0, 51, 51));
        jTextField1_LastName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_LastNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 232, -1));

        jTextField1_Val_FindKey.setBackground(new java.awt.Color(153, 255, 204));
        jTextField1_Val_FindKey.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1_Val_FindKey.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1_Val_FindKey.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1_Val_FindKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_Val_FindKeyActionPerformed(evt);
            }
        });
        jTextField1_Val_FindKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_Val_FindKeyKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1_Val_FindKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 405, 30));

        jTextField_Phone.setBackground(new java.awt.Color(192, 246, 219));
        jTextField_Phone.setForeground(new java.awt.Color(0, 51, 51));
        jTextField_Phone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 232, 26));

        jRadioButtonMale.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jRadioButtonMale.setForeground(new java.awt.Color(77, 249, 88));
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jRadioButtonFemale.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jRadioButtonFemale.setForeground(new java.awt.Color(77, 249, 88));
        jRadioButtonFemale.setText("Female");
        jPanel1.add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jDateChooserBirthDate.setBackground(new java.awt.Color(192, 246, 219));
        jDateChooserBirthDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooserBirthDate.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jDateChooserBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 232, -1));

        jTextArea_Address.setBackground(new java.awt.Color(192, 246, 219));
        jTextArea_Address.setColumns(20);
        jTextArea_Address.setForeground(new java.awt.Color(0, 51, 51));
        jTextArea_Address.setRows(5);
        jTextArea_Address.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea_Address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 233, 106));

        jButtonAddStudent.setBackground(new java.awt.Color(153, 153, 255));
        jButtonAddStudent.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jButtonAddStudent.setForeground(new java.awt.Color(0, 51, 51));
        jButtonAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        jButtonAddStudent.setText("Add");
        jButtonAddStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 109, 43));

        jButtonDelete.setBackground(new java.awt.Color(255, 153, 153));
        jButtonDelete.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(0, 51, 51));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minus.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 106, 43));

        jTableStd.setBackground(new java.awt.Color(153, 255, 204));
        jTableStd.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jTableStd.setForeground(new java.awt.Color(51, 51, 51));
        jTableStd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Sex", "BirthDate", "Phone", "Address"
            }
        ));
        jTableStd.setSelectionBackground(new java.awt.Color(0, 51, 51));
        jTableStd.setSelectionForeground(new java.awt.Color(70, 249, 83));
        jTableStd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStdMouseClicked(evt);
            }
        });
        jTableStd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableStdKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableStd);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 628, 512));

        jTextField1_FirstName.setBackground(new java.awt.Color(192, 246, 219));
        jTextField1_FirstName.setForeground(new java.awt.Color(0, 51, 51));
        jTextField1_FirstName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_FirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 232, -1));

        jButtonEdit.setBackground(new java.awt.Color(237, 237, 33));
        jButtonEdit.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(0, 51, 51));
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        jButtonEdit.setText("Update");
        jButtonEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 106, 43));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 3, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(77, 249, 88));
        jLabel10.setText("Enter Search Value: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 50));

        jTextField1_stdID.setBackground(new java.awt.Color(192, 246, 219));
        jTextField1_stdID.setForeground(new java.awt.Color(0, 51, 51));
        jTextField1_stdID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1_stdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_stdIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_stdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(77, 249, 88));
        jLabel8.setText("Id:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_stdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_stdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_stdIDActionPerformed

    private void jTextField1_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_FirstNameActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // Get data from Text Field
        String fname = jTextField1_FirstName.getText();
        String lname = jTextField1_LastName.getText();
        String phone = jTextField_Phone.getText();
        String address = jTextArea_Address.getText();
        int id = Integer.valueOf(jTextField1_stdID.getText());

        // Male by default. Female by Choice
        String sex = "Male";
        if (jRadioButtonFemale.isSelected()) {
            sex = "Female";
        }

        if (verifyText()) {
            // set date format
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateFormat.format(jDateChooserBirthDate.getDate());

            std.insertUpdateDeleteStudent('u', id, fname, lname, sex, bdate, phone, address);
            ManageStdForm2.jTableStd.setModel(new DefaultTableModel(null, new Object[]{"id", "firstName", "lastName", "sex", "birth", "phone", "address"}));
            std.fillStudentJtable(ManageStdForm2.jTableStd, "");
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    // Info appear back at input when arrow key goes Up or Down
    private void jTableStdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableStdKeyReleased
        // While Arrow Key moving Up or Down info Appear at Input
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            
            int rowIndex = jTableStd.getSelectedRow();
            jTextField1_stdID.setText(model.getValueAt(rowIndex, 0).toString());
            jTextField1_FirstName.setText(model.getValueAt(rowIndex, 1).toString());
            jTextField1_LastName.setText(model.getValueAt(rowIndex, 2).toString());
            jTextField_Phone.setText(model.getValueAt(rowIndex, 5).toString());
            jTextArea_Address.setText(model.getValueAt(rowIndex, 6).toString());

            if (model.getValueAt(rowIndex, 3).toString().equals("Male")){
                jRadioButtonMale.setSelected(true);
                jRadioButtonFemale.setSelected(false);
            }
            else
            {
                jRadioButtonFemale.setSelected(true);
                jRadioButtonMale.setSelected(false);
            }

            Date bdate;
            try{
                bdate = new  SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
                jDateChooserBirthDate.setDate(bdate);
            } catch (ParseException ex) {
                Logger.getLogger(ManageStdForm2.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jTableStdKeyReleased
    
    // like the above by when clicked
    private void jTableStdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStdMouseClicked
        // update student info back to Input Row
        int rowIndex = jTableStd.getSelectedRow();

        // reflect Sex to input row
        if (model.getValueAt(rowIndex, 3).toString().equals("Male")){
            jRadioButtonMale.setSelected(true);
            jRadioButtonFemale.setSelected(false);
        }
        else{
            jRadioButtonFemale.setSelected(true);
            jRadioButtonMale.setSelected(false);
        }

        // Reflect student info to input row
        jTextField1_stdID.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField1_FirstName.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField1_LastName.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_Phone.setText(model.getValueAt(rowIndex, 5).toString());
        jTextArea_Address.setText(model.getValueAt(rowIndex, 6).toString());

        // 
        Date bdate;
        try {
            // create Obj with date format and parse it with value at given Row and Column 4 (Birthdate column)
            bdate = new  SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooserBirthDate.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(ManageStdForm2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTableStdMouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

        // checking if TextField is Empty
        if (jTextField1_stdID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No Student Selected");
        }
        else {
            int id = Integer.valueOf(jTextField1_stdID.getText());

            std.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);
            // re-count student from table
            MainForm.jLabel2_stdCount.setText("Student Count: " + Integer.toString(MyFunction.countData("student")));

            jTableStd.setModel(new DefaultTableModel(null, new Object[] {"Id", "First Name", "Last Name", "Sex", "Birthday", "Phone", "Address"}));
            std.fillStudentJtable(jTableStd, "");

            // Set all input row to be Empty/Default again
            jTextField1_FirstName.setText("");
            jTextField1_LastName.setText("");
            jTextField1_stdID.setText("");
            jTextArea_Address.setText("");
            jTextField_Phone.setText("");
            jRadioButtonFemale.setSelected(false);
            jRadioButtonMale.setSelected(false);
            jDateChooserBirthDate.setDate(null);

        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStudentActionPerformed
        // Get data from Text Field
        String fname = jTextField1_FirstName.getText();
        String lname = jTextField1_LastName.getText();
        String phone = jTextField_Phone.getText();
        String address = jTextArea_Address.getText();

        // Male by default. Female by Choice
        String sex = "Male";
        if (jRadioButtonFemale.isSelected()) {
            sex = "Female";
        }

        if (verifyTextNoId()) {
            // set date format
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String bdate = dateFormat.format(jDateChooserBirthDate.getDate());

            // Take data from input. Put it in a student Obj and add it to the Table
            student std = new student();
            std.insertUpdateDeleteStudent('i', null, fname, lname, sex, bdate, phone, address);
            // re-count student after Insert new student
            MainForm.jLabel2_stdCount.setText(" Students Count : " + Integer.toString(MyFunction.countData("student")));

            // update by re-fill table
            ManageStdForm2.jTableStd.setModel(new DefaultTableModel(null, new Object[]{"Id", "First Name", "Last Name", "Sex", "Birthday", "Phone", "Address"}));
            std.fillStudentJtable(ManageStdForm2.jTableStd, "");

        }
    }//GEN-LAST:event_jButtonAddStudentActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jTextField_PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyTyped
        // Allow Only Numbers (for Phone Number):
        if (!Character.isDigit(evt.getKeyChar())) {
            String enterChar = String.valueOf(jTextField_Phone.getText());
            System.out.println("This is not a number !!! ");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PhoneKeyTyped

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    private void jTextField1_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_LastNameActionPerformed

    private void jTextField1_Val_FindKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_Val_FindKeyKeyReleased
        // almost like FindKeyType but smoother
        // Set new Table with new Input each Update
        jTableStd.setModel(new DefaultTableModel(null, new Object[]{"Id", "First Name", "Last Name", "Sex", "Birthday", "Phone", "Address"}));
        std.fillStudentJtable(jTableStd, jTextField1_Val_FindKey.getText());
    }//GEN-LAST:event_jTextField1_Val_FindKeyKeyReleased

    private void jTextField1_Val_FindKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_Val_FindKeyActionPerformed
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_jTextField1_Val_FindKeyActionPerformed

    public boolean verifyTextNoId() {
        if (jTextField1_FirstName.getText().equals("")
                || jTextField1_LastName.getText().equals("")
                || jTextField_Phone.getText().equals("")
                || jTextArea_Address.getText().equals("")
                || jDateChooserBirthDate.getDate() == null) 
        {
            JOptionPane.showMessageDialog(null, "One Or More Empty Field");
            return false;
        } 
        // choose a Date higher than the current date
        else if (jDateChooserBirthDate.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "No Student from the Future are Allowed");
            return false;
        } // return True by Default if not False
        else {
            return true;
        }
    }
    
    
    // Checking if any Text field Empty
    public boolean verifyText() {
        if (jTextField1_FirstName.getText().equals("")
                || jTextField1_LastName.getText().equals("")
                || jTextField_Phone.getText().equals("")
                || jTextArea_Address.getText().equals("")
                || jTextField1_stdID.getText().equals("")
                || jDateChooserBirthDate.getDate() == null) 
        {
            JOptionPane.showMessageDialog(null, "One Or More Empty Field");
            return false;
        } 
        // choose a Date higher than the current date
        else if (jDateChooserBirthDate.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "No Student from the Future are Allowed");
            return false;
        } // return True by Default if not False
        else {
            return true;
        }
    }
        
        
    int rowIndex;    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStdForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStdForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStdForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStdForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStdForm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddStudent;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private com.toedter.calendar.JDateChooser jDateChooserBirthDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableStd;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField1_FirstName;
    private javax.swing.JTextField jTextField1_LastName;
    private javax.swing.JTextField jTextField1_Val_FindKey;
    private javax.swing.JTextField jTextField1_stdID;
    private javax.swing.JTextField jTextField_Phone;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
